- id: '1770603165144'
  name: Evening lights
  entities:
    light.brass_ball:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: Brass Ball
      supported_features: 0
      state: 'on'
    light.old_goldie:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: Old Goldie
      supported_features: 0
      state: 'on'
    light.schoolhouse:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 9000
      min_mireds: 111
      max_mireds: 400
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 166
      color_temp_kelvin: 3621
      color_temp: 276
      hs_color:
      - 27.061
      - 42.206
      rgb_color:
      - 255
      - 196
      - 147
      xy_color:
      - 0.445
      - 0.372
      friendly_name: Schoolhouse
      supported_features: 32
      state: 'on'
    light.blue_school_lamp:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: Blue School Lamp
      supported_features: 0
      state: 'on'
    light.swing_ball_lamp:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: Swing Ball Lamp
      supported_features: 0
      state: 'on'
  metadata: {}
  icon: mdi:ceiling-light-multiple
- id: '1771015658049'
  name: Patio Lights
  entities:
    update.right_flood_firmware:
      auto_update: false
      display_precision: 2
      installed_version: '0x01001d08'
      in_progress: false
      latest_version:
      release_summary:
      release_url:
      skipped_version:
      title:
      update_percentage:
      device_class: firmware
      entity_picture: https://brands.home-assistant.io/_/zha/icon.png
      friendly_name: Right Flood Firmware
      supported_features: 23
      state: unknown
    button.right_flood_identify:
      device_class: identify
      friendly_name: Right Flood Identify
      state: unknown
    light.right_flood:
      supported_color_modes:
      - brightness
      color_mode: brightness
      brightness: 254
      off_with_transition: false
      off_brightness:
      friendly_name: Right Flood
      supported_features: 40
      state: 'on'
    select.right_flood_start_up_behavior:
      options:
      - 'Off'
      - 'On'
      - Toggle
      - PreviousValue
      friendly_name: Right Flood Start-up behavior
      state: 'On'
    number.right_flood_start_up_current_level:
      min: 0
      max: 255
      step: 1
      mode: auto
      friendly_name: Right Flood Start-up current level
      state: '254'
    light.left_flood:
      supported_color_modes:
      - brightness
      color_mode: brightness
      brightness: 254
      off_with_transition: false
      off_brightness:
      friendly_name: Left Flood
      supported_features: 40
      state: 'on'
  metadata: {}
  icon: mdi:car-parking-lights
