- id: '1770603165144'
  name: Evening lights
  entities:
    light.brass_ball:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: Brass Ball
      supported_features: 0
      state: 'on'
    light.old_goldie:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: Old Goldie
      supported_features: 0
      state: 'on'
    light.schoolhouse:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 9000
      min_mireds: 111
      max_mireds: 400
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 140
      color_temp_kelvin: 2500
      color_temp: 400
      hs_color:
      - 29.704
      - 68.627
      rgb_color:
      - 255
      - 166
      - 80
      xy_color:
      - 0.526
      - 0.387
      friendly_name: Schoolhouse
      supported_features: 32
      state: 'on'
    light.blue_school_lamp:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: Blue School Lamp
      supported_features: 0
      state: 'on'
    light.swing_ball_lamp:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: Swing Ball Lamp
      supported_features: 0
      state: 'on'
    light.living_room_tapo_1_tapo_smart_plug_2:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: Rembrandt
      supported_features: 0
      state: 'on'
  metadata: {}
  icon: mdi:ceiling-light-multiple
- id: '1739700000001'
  name: All lights on
  icon: mdi:lightbulb-group
  entities:
    light.schoolhouse:
      state: 'on'
      brightness: 255
      color_temp_kelvin: 4000
    light.brass_ball:
      state: 'on'
    light.old_goldie:
      state: 'on'
    light.blue_school_lamp:
      state: 'on'
    light.swing_ball_lamp:
      state: 'on'
    light.living_room_tapo_1_tapo_smart_plug_2:
      state: 'on'
    light.rectolamp:
      state: 'on'
  metadata: {}
